### PR TITLE
Enhancement distributed worlds

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Various fixes:
* [x] fix errors with unknown Appearance fields in Thymio2Ball.proto
* [x] fix controller file open by default in khepera.wbt
* [x] fix DistanceSensor type in IprHd6ms90.proto
* [x] add nao_soccer_player controller to the main Makefile
* [x] fix overlay default setting and empty url field warning in sick_terrain_scanning.wbt

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Do you know if there is a particular reason why the controller `nao_soccer_player` is not compiled (and the binary is not distributed)?

**Comment by DavidMansolino** [comment]
> Do you know if there is a particular reason why the controller `nao_soccer_player` is not compiled (and the binary is not distributed)?

I don't see any reason...

> Can one of the admins verify this patch?

@stefaniapedrazzi I just did re-added you to the list of Jenkins admins

**Comment by omichel** [comment]
I don't know either...

**Comment by fabienrohrer** [comment]
It looks like an error for me too.

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
I fixed another minor issue with `.display.wbproj`.

:+1:

**Comment by DavidMansolino** [comment]
:eyes:

**Pull request merged**
