### PR TITLE
Fix IE 11 support

### PR DESCRIPTION
**Pull request by fabienrohrer**
This line is required to make IE11 work smoothly.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
👎

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
This is fine.
But it has to be applied to all the pages using `webots.min.js`, i.e. at least to robotbenchmark and the HTML page created for the animation (`resources/web/templates/x3d_playback.html`).

I will update robotbenchmark in the existing PR https://github.com/omichel/robotbenchmark/pull/324

**Comment by fabienrohrer** [comment]
Well spotted, thank you, I test this for the X3D playback page.

**Comment by fabienrohrer** [comment]
`x3d_playback.html` was suffering indeed the same issue:

Capture d’écran 2019-04-29 à 14 25 28

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
