### PR TITLE
Fix Braitenberg Controller

### LINKED ISSUE #186: Robot not moving in pioneer2.wbt
**Describe the Bug**
The robot in pioneer2.wbt is not moving:
* in the R2019a revision 1 world opened with Webots R2018b the robot moves
* in the R2018b world opened with Webots R2019a revision 1 the robot doesn't move

**Steps to Reproduce**
1. Open and start pioneer2.wbt

**System**
 - Operating System: Linux Ubuntu 18.04

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #186

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
The issue is fixed.
But why it doesn't work if the arrays are defined later inside the if?

**Comment by DavidMansolino** [comment]
Because then the `temp_matrix` pointer points to the array outside of its definition scope.

**Pull request merged**
