### PR TITLE
Fix generate diff bug

### LINKED ISSUE #666: Failure of the generate_diff.py script
**Describe the Bug**
This script is often failing on Travis and AppVeyor, e.g.:
  - https://travis-ci.com/omichel/webots/builds/117098995
  - https://ci.appveyor.com/project/omichel/webots/builds/25578834

With the following stack:
```
if ($env:APPVEYOR_SCHEDULED_BUILD -ne "True" -and $env:APPVEYOR_REPO_TAG -ne "true") { C:\\Python37-x64\\python.exe $env:WEBOTS_HOME\\tests\\sources\\generate_diff.py $env:APPVEYOR_REPO_COMMIT $env:APPVEYOR_REPO_NAME }
C:\\Python37-x64\\python.exe : Traceback (most recent call last):
At line:1 char:88
+ ... e "true") { C:\\Python37-x64\\python.exe $env:WEBOTS_HOME\\tests\\sou ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\projects\webots\\tests\\sources\\generate_diff.py", line 64, in <module>
    url = j["items"][0]["pull_request"]["url"]
IndexError: list index out of range
Command executed with exception:   File "C:\projects\webots\\tests\\sources\\generate_diff.py", line 64, in <module>
    url = j["items"][0]["pull_request"]["url"]
IndexError: list index out of range
```
This perfectly makes sense, we are trying to get the pull-request information for a branch for which there is currently no pull-request (at least for the first commit).

For example on PR #665, I did create and push the two first commits without openning the pull-request => the tests failed, then I open the pull-request and did the third commit => the test passed.

This is not very nice as it shows failled commits (whereas nothing is wrong with them).

### PR DESCRIPTION
**Pull request by omichel**
Fixes #666 😈

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by fabienrohrer** [comment]
To prove it's working, you could create a new PR with this patch. If the first test pass, then it's ok.

**Comment by DavidMansolino** [comment]
> To prove it's working, you could create a new PR with this patch. If the first test pass, then it's ok.

New branch you mean

**Comment by fabienrohrer** [comment]
yes

**Comment by omichel** [comment]
The second commit which passed was successfully tested before I created the PR.

**Comment by omichel** [comment]
The third one was passed after the PR was created.

**Comment by fabienrohrer** [comment]
Ok, thank you (it was impossible to see in the log).

**Comment by fabienrohrer** [comment]
On the second test, I don't see any AppVeyor log (while I precisely expect to see a success here) is it regular?

| |
|---|
| Capture d’écran 2019-06-27 à 12 20 50 |

**Comment by omichel** [comment]
Yes, for some reason the appveyor test didn't start on the second commit...

**Comment by fabienrohrer** [comment]
It is unfortunately precisely the way to evaluate the success of this patch. Therefore I would recommend to close this branch and create a new one proving it's working.

**Pull request closed without merging**
