### PR TITLE
Add links from docs to github folders and files

### PR DESCRIPTION
**Pull request by omichel**
Links from the documentation to github folder and files can be very helpful.

Test: https://www.cyberbotics.com/doc/guide/samples-demos?version=fix-add-links-from-doc-to-github-folders-and-files

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by omichel** [comment]
👍

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by omichel** [comment]
Thank you!

**Pull request merged**
