### PR TITLE
Upgraded Qt to version 5.12.2 on Windows

### PR DESCRIPTION
**Pull request by omichel**
MSYS2 has upgraded Qt to version 5.12.2. We need to catch-up with that on the master branch, so that our installation instructions remain valid.

👍

### CODE REVIEW

**Comment by DavidMansolino** [comment]
👀

**Comment by DavidMansolino** [comment]
I am still having issues with this PR (I did re-install completely my msys environment to make sure the installation instructions are not broken and I have issues with the `zlib1` dll). I will keep investigating.

**Comment by DavidMansolino** [comment]
👍

**Comment by omichel** [comment]
👍 (I need your approval to merge)

**Comment by DavidMansolino** [comment]
(oups sorry bad habit)

**Pull request merged**
