### PR TITLE
Improve tutorial 2

### PR DESCRIPTION
**Pull request by ValerieMichel**
Test link: https://cyberbotics.com/doc/guide/tutorial-2-modification-of-the-environment-20-minutes?version=fix-tutorial-2

### CODE REVIEW

**Comment by ValerieMichel** [comment]
It would be better if links to the reference manual open in a new tab.

 **Hands-on #1**: Make sure the `my_first_simulation.wbt` world file is open
The world from "Sample worlds" of Webots is different from the world we saved in Tutorial 1 (3 wooden boxes in supplement).

The titles under the 2 figures-charts are inverted: (#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-a-physical-bounding-object-and-being-in-the-dynamical-environment) and (#def-use-mechanism-on-the-sphere-node-called-ball_geometry)

The (#your-first-rigid-body-in-webots) figure is not the one we obtain: subdivision field is different, the scene tree is different (DEF BALL solid !!!)

The first paragraph of geometries is not clear: does "physical context" correspond to bounding object?

(#def-use-mechanism-on-the-sphere-node-called-ball_geometry) figure: they should be no walls.

The solution is located in the solution directory in `obstacle.wbt`.
Is it in File/Open Sample Worlds/samples/tutorials/obstacles.wbt?

In this obstacles.wbt world, we find DEF BALL solid not introduced before and also DEF WALL_X solid. We are supposed to apply DEF/USE to the shape only.

**Comment by ValerieMichel** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
> It would be better if links to the reference manual open in a new tab.

You should open an issue about it as it requires some programming.

> Hands-on #1: Make sure the my_first_simulation.wbt world file is open
> The world from "Sample worlds" of Webots is different from the world we saved in Tutorial 1 (3 wooden > boxes in supplement).

It is correct in the current master branch (the world has 3 wooden boxes).

> The titles under the 2 figures-charts are inverted: (#the-simplest-model-of-a-rigid-body-in-webots-having-a-graphical-representation-a-physical-bounding-object-and-being-in-the-dynamical-environment) and (#def-use-mechanism-on-the-sphere-node-called-ball_geometry)

I believe it is correct. If that's not clear for you, can you propose something to clarify it (commit it)?

> The (#your-first-rigid-body-in-webots) figure is not the one we obtain: subdivision field is different, the scene tree is different (DEF BALL solid !!!)

Can you remake the screenshot and commit it?

> The first paragraph of geometries is not clear: does "physical context" correspond to bounding object?

Yes. Can you propose a better text for that?

> (#def-use-mechanism-on-the-sphere-node-called-ball_geometry) figure: they should be no walls.

Can you make a new screenshot for that?

> The solution is located in the solution directory in obstacle.wbt.
> Is it in File/Open Sample Worlds/samples/tutorials/obstacles.wbt?

Yes, should you clarify this?

> In this obstacles.wbt world, we find DEF BALL solid not introduced before and also DEF WALL_X solid. We are supposed to apply DEF/USE to the shape only.

We should then probably remove these DEF. Can you modify this file accordingly and commit it on this PR?

**Comment by ValerieMichel** [comment]
About opening a link in a new tab, we can  "ctrl" and click or right-click the link and choose "Open Link in New Tab" (Firefox). Is it useful to program something?

**Comment by ValerieMichel** [comment]
👍

**Comment by ValerieMichel** [comment]
👍

**Pull request merged**
