### PR TITLE
Blog page for Webots R2019b

### PR DESCRIPTION
**Pull request by fabienrohrer**
Preview: https://www.cyberbotics.com/doc/blog/Webots-2019-b-release?version=doc-blog-page-for-webots-r2019b

  - [x] Generate thumbnails.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
@DavidMansolino Could I let you take the lead on this PR and add your contribution?

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Comment by stefaniapedrazzi** [comment]
I did some modifications to the text trying to make it more attractive

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
👍

**Comment by fabienrohrer** [comment]
Thank you everybody.
Just to be clear, I put my name as an author here in order to personalize the announcement: let's put another name on the next time :-)

=> I will regenerate the thumbnails and merge this.

**Pull request merged**
