### PR TITLE
Fix make cleanse on Windows

### PR DESCRIPTION
**Pull request by fabienrohrer**
My recent commit #559 broke `make cleanse` on Windows

### CODE REVIEW

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
👁

**Comment by DavidMansolino** [comment]
Sorry but I still have the following issue on Windows with ``make cleanse``:
```
make[2]: *** No rule to make target 'libraries.Makefile', needed by 'clean'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by DavidMansolino** [comment]
The clean rule depends on ``libraries.Makefile``

**Pull request merged**
