### PR TITLE
Add Simple Example of Hinge2Joint and BallJoint

### LINKED ISSUE #451: Add Simple Example of Hinge2Joint and BallJoint
We are currently missing a simple example with these two type of joints.
The example should be similar to the samples/devices/rotational_motor one.

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #451

  - [x] Hinge2Joint
  - [x] BallJoint
  - [x] Doc/Changelog: https://www.cyberbotics.com/doc/guide/samples-devices?version=enhancement-joint-samples#motor-wbt

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
👍

**Pull request merged**
