### PR TITLE
Skip AppVeyor test on merge

### PR DESCRIPTION
**Pull request by omichel**
In this PR, we want to avoid launching useless AppVeyor source tests each time a branch is merged in master, revision or develop.

### CODE REVIEW

**Comment by omichel** [comment]
Replaced by #697.

**Comment by omichel** [comment]
👍 (let's see when we merge this PR if it works 😄)

**Comment by DavidMansolino** [comment]
Isn't this going to cause a problem when we will want to run the nightly source test?

**Comment by omichel** [comment]
Yes, but I see no better option than creating a new .appveyor.yml file for the nightly source tests... 😒

**Pull request merged**
