### PR TITLE
Fix animation

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Addresses #510.
Fix jumping to a previous animation pose:
* store initial state in JSON file (only for nodes that will change during the animation recording)
* remove optimized search mechanism in `webots.min.js` and search in all the steps for updates

Other improvements:
* remove duplicated pause and play images used for the animation
* fix other wrong/unused exported lines
* restore correct appearance of pendulum in inverted_pendulum.wbt (broken when switching to PBRAppearance)

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
When measuring the performance of jumping from one pose to the other in this branch and on robotbenchmark, the slow down of removing the loop optimization is quite big (in pick and place jumping from start to end takes 157ms instead of 15ms) but on my PC the update time is acceptable.

I will try to speed it up by storing in the animation JSON file only the ids that changes and not all the possible ids.

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Pull request merged**
