### PR TITLE
Remove Duplicated Textures

### PR DESCRIPTION
**Pull request by DavidMansolino**
Follow-up of #220 for develop.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
I would prefer JPEG images to PNG images as they are significantly smaller and with a 95% quality rate, you can hardly see the difference with the original PNG image.

**Comment by omichel** [comment]
I believe we should use PNG only when we need transparency/translucency.

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
