### PR TITLE
Update Webots version to R2019a revision 2

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Ditto.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
Personally I think that changing the version on the branch should be the first thing we do.
Especially for major version change and for guaranteeing compatibility this is very important.

**Comment by DavidMansolino** [comment]
> Personally I think that changing the version on the branch should be the first thing we do.

I fully agree, we should do this right after the release.

**Pull request merged**
