### PR TITLE
Fix Khepera4 Ground Sensors Calibration

### LINKED ISSUE #319: Khepera 4 Ground Sensors does not Detect Colors
**Describe the Bug**
The ground sensors of the khepera4 are 'infra-red' type but they don't detect the color changes, this is probably because the range is very big compared to the distance robot-floor.

**Steps to Reproduce**
1. Open the khepera4.wbt world
2. Launch the simulation and check the value of the ground sensors in the robot-window.
3. Change the CircleArena.appearance to white => check value of ground sensors
4. Change the CircleArena.appearance to black => check value of ground sensors => they are similar to step 3.

**Expected behavior**
It should be possible to differentiate between a black and a white floor.

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #319.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
Thanks to this corrected calibration it is now possible to distinguish ground colors:
Capture du 2019-04-04 12-06-33

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
