### PR TITLE
Fix texture downscaling (alternative)

### LINKED ISSUE #171: Improve linear_motor.wbt Node hierarchy
**Describe the Bug**
The node hierarchy of the linear motor simulation should be improved. It does contain useless group node and empty transform node.

Furthermore with the AMD radeon R5 the ruler is to much transparent.
Nvidia GTX 980:
linear_motor

Radeon R5:
linear_motor

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix #171

### CODE REVIEW

**Comment by fabienrohrer** [comment]
This solution works but is unfortunately very slow.

**Comment by omichel** [comment]
Why is it slower than what is done by Qt? Is it a different algorithm?

**Comment by fabienrohrer** [comment]
Yes, this is a different algorithm but the idea is globally the same.

As expected, in Qt, the image smooth-scale algorithm is split into several optimized parts, the main entry point use 2D transform matrix:
http://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/image/qimage.cpp#n2767
I think the scale is done in this function:
http://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/painting/qimagescale.cpp#n540
I think that the blur (which is actually the part creating alpha issue for sure) is done in this function:
https://code.woboq.org/qt5/qtbase/src/widgets/effects/qpixmapfilter.cpp.html#_Z12qt_blurImageP8QPainterR6QImagedbbi
The blur is actually done using a QPainter which is also a big part of Qt.

I also tried to blur using QPainter and qt_blurImage(), but it suffers of the same alpha bug (showing it comes from this part).

**Comment by fabienrohrer** [comment]
I'm trying another approach about to apply a blur at the same time as the scale down.

**Comment by fabienrohrer** [comment]
Drop for #197

**Pull request closed without merging**
