### PR TITLE
Fix display.wbt sample

### LINKED ISSUE #162: Emoticons not visible in MyBot display
**Describe the Bug**
The emoticon images displayed on the MyBot display are not visible.

**Steps to Reproduce**
1. Open and run `display.wbt`

**Screenshots**
display_buggy

**System**
 - Operating System:Linux Ubuntu 18.04
 - Graphics Card: NVIDIA GeForce GT 740

### PR DESCRIPTION
**Pull request by fabienrohrer**
Fix #162

- [x] Fix broken perspectives.
- [x] Choose a simpler background (without yellow to avoid bad yellow blob recognition, with a lower light contract).
- [x] Remove the Display.emissiveColor which reduce the baseColor effect.
- [x] Improve collision avoidance algorithm.
- [x] Remove Ground filtering.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Perspectives load has been broken in this commit: https://github.com/omichel/webots/commit/edefcdfa61ebd15a15408ac32153fb03f567d5e0

I just fixed it here.

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
👍

**Comment by DavidMansolino** [comment]
:eyes:

**Pull request merged**
