### PR TITLE
Update Webots version to R2019b

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Ditto.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
I tested locally and I don't have any compilation issue.
I will check deeply once #421 is merged and included in this PR as it could cause some conflicts.

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by DavidMansolino** [comment]
It seems there is still an issue with the test suite.
I will check the config file.

**Comment by DavidMansolino** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
oops, I saw the green tick (and not the yellow dot) and I though that the test was passed.
Locally everything is working correctly. It is strange that the compilation of the test suite worlds blocked on the jenkins machine.

**Comment by DavidMansolino** [comment]
I think that it was not the compilation in itself but Webots was stuck at startup:
```
OpenGL version      : 4.5.0 NVIDIA 384.130


### api test

FAILURE: Some tests have not been executed
- expected number of worlds: 123
- number of worlds actually tested: 0)

Webots complete STDOUT log:

Webots complete STDERR log:

### physics test

FAILURE: Some tests have not been executed
- expected number of worlds: 24
- number of worlds actually tested: 0)
```

Bu this is probably fine now that welcome dialog is not displayed anymore.

**Comment by stefaniapedrazzi** [comment]
I confirm the test_suite is working now on the develop branch.

**Pull request merged**
