### PR TITLE
Fix Test Suite 'TRAVIS' Dependency

### PR DESCRIPTION
**Pull request by DavidMansolino**
This should fix the problem when running the test suite locally.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
I confirm that now it works, thanks.

Is there a reason why the execution flag for `test_suite.py` has been removed?

Just for note, the compilation of the test suite resources is now much more verbose:
```
stefi@libeccio:~/develop/webots/tests$ python test_suite.py 
make: Entering directory '/home/stefi/develop/webots/tests'
make[1]: Entering directory '/home/stefi/develop/webots/tests/api'
make[1]: Entering directory '/home/stefi/develop/webots/tests/protos'
make[1]: Entering directory '/home/stefi/develop/webots/tests/parser'
make[1]: Entering directory '/home/stefi/develop/webots/tests/rendering'
make[1]: Entering directory '/home/stefi/develop/webots/tests/physics'
make[2]: Entering directory '/home/stefi/develop/webots/tests/api/controllers'
make[2]: Entering directory '/home/stefi/develop/webots/tests/api/plugins/physics'
make[2]: Entering directory '/home/stefi/develop/webots/tests/rendering/controllers'
make[2]: Entering directory '/home/stefi/develop/webots/tests/physics/controllers'
make[2]: Entering directory '/home/stefi/develop/webots/tests/protos/controllers'
make[2]: Entering directory '/home/stefi/develop/webots/tests/parser/controllers'
make[2]: Entering directory '/home/stefi/develop/webots/tests/api/plugins/remote_controls'
make[2]: Entering directory '/home/stefi/develop/webots/tests/api/plugins/robot_windows'
# make release robot_window
# make release copy_args_in_custom_data
# make release hidden_parameter_single
...
```

**Comment by DavidMansolino** [comment]
> Is there a reason why the execution flag for test_suite.py has been removed?

No, I did noticed that sometimes when editing a file in Github the flag is removed, this is probably what happened, I will re-add it in this PR.

>Just for note, the compilation of the test suite resources is now much more verbose:

That's normal, now we are passing the path to make, because before the test suite was not working if launched from outside the 'webots/tests' folder. But I have an idea to improve the compilation outputs, let me try.

**Comment by DavidMansolino** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Pull request merged**
