### PR TITLE
Hotfix Too Big Images in Docs

### PR DESCRIPTION
**Pull request by DavidMansolino**
This fi is very urgent because after cleaning the cache it takes me 25seconds to load completely this page https://www.cyberbotics.com/doc/guide/samples-devices (event from the office).

This PR just creates thumbnails and use them in the doc, it does not implement modal images.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Thank you, it seems to be a good first step, keeping the sources is important.

**Comment by DavidMansolino** [comment]
In comparison, this page loads almost instantaneously: https://cyberbotics.com/doc/guide/samples-devices?version=doc-thumbmail

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Comment by fabienrohrer** [comment]
Some images are not centered correctly:

Capture d’écran 2019-05-15 à 17 26 25

I'm trying to fix this.

**Comment by DavidMansolino** [comment]
We should probably simply change the table headers by `:---:` I can do it if you want.

**Comment by fabienrohrer** [comment]
oh yeah, it's much simpler that what I had in mind :-D

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
