### PR TITLE
Fix Light Doc.

### PR DESCRIPTION
**Pull request by DavidMansolino**
ditto

### CODE REVIEW

**Comment by DavidMansolino** [comment]
This was not updated when introducing HDR.

**Comment by DavidMansolino** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
The documentation of the `ambientIntensity` is outdated. I'm just writing an issue about this.

**Comment by DavidMansolino** [comment]
Yes indeed, it does influence non-PBR object only.

**Comment by stefaniapedrazzi** [comment]
> Yes indeed, it does influence non-PBR object only.

Yes, but even for non-PBR objects it doesn't work as documented.

**Comment by stefaniapedrazzi** [comment]
By the way it seems that `ambientIntesity` cannot be greater than 1:

```
WARNING: PointLight: Invalid 'ambientIntensity' changed to 1. The value should be in range [0, 1].
```

**Comment by DavidMansolino** [comment]
> By the way it seems that ambientIntesity cannot be greater than 1:

It should probably... but this should not be changed on this branch, I will keep therefore keep ambientIntesity bounded on this branch.

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
