### PR TITLE
Fix file path in doc

### PR DESCRIPTION
**Pull request by DavidMansolino**
@physar thank you for this contribution, feel free to open PR on our repository to fix such errors.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
:+1:

**Comment by DavidMansolino** [comment]
@physar can you please update your branch with our master branch so that we can merge this PR? Or give us write access to this branch.

**Comment by physar** [comment]
Branch is updated. Got now an error that the head branch is updated.

**Comment by physar** [comment]
If you are interested, I also made a Matlab Live Script to control remotely a Kephera robot started in Webots, as described in the tutorial:

https://staff.fnwi.uva.nl/a.visser/research/roboresc/2019/matlab_tcpip_webots.mlx

Matlab Live Scripts have the advantage that you can add explanations to the code.

**Comment by omichel** [comment]
It's merged thank you. We will have a look at your MATLAB Live Script. That sounds interesting.

**Pull request merged**
