### PR TITLE
Fix Cylinder boundingObject representation

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Address #411.

Tasks:
* [x] fix orientation of Cylinder outline mesh
* [x] set minimum subdivision (16) value for boundingObject Cylinder and Capsule
    -> make it clear that the ODE shape will be a real cylinder even if the subdivision value used for the graphical mesh is low

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
I was wondering if we had to warn the user about the minimum subdivision value used for bounding objects.
Changing it silently didn't seem very user-friendly, on the other hand having lot of warnings at load or when adding nodes was bad as well.

So the current implementation is:
* no warnings on node finalization
* no warnings for USE nodes
* a warning is displayed if the subdivision field is changed after the node creation (for example when explicitly setting it from the scene tree)

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by DavidMansolino** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
It is working fine.

But in case of USE node, the warning is sometimes displayed when in my point of view it should not. For example if you have a Shape=>Cylinder in the children field of a Solid node and then you use the cylinder in the bounding object the warning is displayed.

You can simply reproduce this in the `khepera3_gripper` world, change the 'CYLINDER_LOAD.CYLINDER_SHAPE.Cylinder.subdivision` field, the warning will be displayed.

Wouldn't it be possible to skip the warning in case of USE node?

**Comment by stefaniapedrazzi** [comment]
Yes, the purpose was to not print warnings in the case of USE nodes.
I tested with a simple example of USE Shape and geometry and it was working as expected.

I will check the khepera world.

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Pull request merged**
