### PR TITLE
webots.min.js: Fix background color

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] Fix JS crash in case there is no background node (cf. above to reproduce the bug)
- [x] Fix the default Background color (black in Webots, white in threejs)
- [x] Log

### To reproduce the bug

- Open `physically_based_rendering.wbt`
- Remove the background
- Open the browser client
- Get this error when picking:
        Capture d’écran 2019-07-29 à 15 34 17

Note:  `threejs` do the assumption that the background is null at several locations, for example [here](https://github.com/mrdoob/three.js/blob/r104/src/scenes/Scene.js#L31).

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Default background:

Capture d’écran 2019-07-29 à 15 49 41

**Comment by stefaniapedrazzi** [comment]
> Fix JS crash in case there is no background node (cf. above to reproduce the bug)

I also fixed this big here #751 : it was enough to replace `undefined` by `null` was enough.

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
:eyes:

**Pull request merged**
