### PR TITLE
Fix Cppcheck Errors.

### PR DESCRIPTION
**Pull request by DavidMansolino**
Cppcheck reports some errors on Travis.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:    (all the cppcheck issues haven't been fixed yet but since I already fixed a lot of them and don't have the time to finish now I would like to already merge these ones).

**Comment by omichel** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
test me

**Pull request merged**
