### PR TITLE
Fix Missing Thumbnail.

### PR DESCRIPTION
**Pull request by DavidMansolino**
This thumbnail was missing.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Thank you!

But we also have to add a white background to `images/web_simulation_network_infrastructure.png` otherwise many parts are not readable when opened with the dark background.

**Comment by fabienrohrer** [comment]
About the transparency issue, it's certainly more general. I propose to fix it simply by adding systematically a white background when rendering the modal window images: https://github.com/omichel/webots/pull/770

**Comment by DavidMansolino** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Pull request merged**
