### PR TITLE
Fixed recompilation of controller with gcc7

### LINKED ISSUE #176: Impossible to Recompile e-puck_position_supervisor Controller from Windows Release
**Describe the Bug**
```
make
# updating e-puck_position_supervisor.d
# compiling e-puck_position_supervisor.c
In file included from e-puck_position_supervisor.c:23:0:
e-puck_position_supervisor.c: In function 'main':
C:\Program Files\Webots/include/controller/c/webots/robot.h:73:27: warning: implicit declaration of function 'fflush'; did you mean 'false'? [-Wimplicit-function-declaration]
 #define wb_robot_step(d) (fflush(NULL) ? wb_robot_step(d) : wb_robot_step(d))
                           ^
e-puck_position_supervisor.c:40:10: note: in expansion of macro 'wb_robot_step'
   while (wb_robot_step(TIME_STEP) != -1) {
          ^~~~~~~~~~~~~
C:\Program Files\Webots/include/controller/c/webots/robot.h:73:34: error: 'NULL' undeclared (first use in this function)
 #define wb_robot_step(d) (fflush(NULL) ? wb_robot_step(d) : wb_robot_step(d))
                                  ^
e-puck_position_supervisor.c:40:10: note: in expansion of macro 'wb_robot_step'
   while (wb_robot_step(TIME_STEP) != -1) {
          ^~~~~~~~~~~~~
C:\Program Files\Webots/include/controller/c/webots/robot.h:73:34: note: each undeclared identifier is reported only once for each function it appears in
 #define wb_robot_step(d) (fflush(NULL) ? wb_robot_step(d) : wb_robot_step(d))
                                  ^
e-puck_position_supervisor.c:40:10: note: in expansion of macro 'wb_robot_step'
   while (wb_robot_step(TIME_STEP) != -1) {
          ^~~~~~~~~~~~~
make: *** [C:/Program Files/Webots/resources/Makefile.include:679: build/release/e-puck_position_supervisor.o] Error 1
```

**Steps to Reproduce**
1. From the release open the `e-puck_matlab.wbt` world
2. Try recompiling the e-puck_position_supervisor controller

**Expected behavior**
The controller should recompile without any problem.

**System**
 -  Operating System: Windows 10 (only from the distribution, working fine from the development environment)

**Additional context**
Probably related to  #154

### PR DESCRIPTION
**Pull request by omichel**
Fixes #176.

### CODE REVIEW

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
👍

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
👍

**Comment by DavidMansolino** [comment]
👀

**Pull request merged**
