### PR TITLE
Bloom in webots.min.js

### PR DESCRIPTION
**Pull request by fabienrohrer**
Aim: Add the bloom post processing in webots.min.js

Apply and improve #408, now possible thanks to #528

- [x] Replicate the bloom rendering pass in `webots.min.js`
- [x] Map the `Viewpoint.bloomThreshold` with `webots.min.js`
- [x] Adjust parameters to reduce the rendering gap.
- [x] Log

Around this PR:

- [x] Fix Viewpoint.bloomThreshold runtime update which was not applied.
- [x] Add a `debug` mode to the `webots.min.js` Makefile in order to build a `webots.debug.js` file which is not minified and obfuscated (very helpful to debug).

### CODE REVIEW

**Comment by fabienrohrer** [comment]
The bloom is applied in a very similar way as the Webots one. I copied almost exactly the shaders we have in Webots.

Here are some results:

| Bloom threshold | Webots | webots.min.js |
|---|---|---| 
| Bloom 0 | webots_bloom_0 | threejs_bloom_0  | 
| Bloom 1 | webots_bloom_1 | threejs_bloom_1 | 

Where to look at:

where to look at

As the bloom input is dealt by `three.js` and has not floating point values bigger than 1.0, then the twinkling effect appearing on saturated edges (the most visible effect of the bloom as implemented in Webots) is almost not visible in this implementation:

| threejs | Webots |
|---|---|
| threejs | webots |

Going further is another story: we have to deal with HDR in the threejs pipeline.
I think the current status is good enough to be merged as it reduces the rendering diff between Webots and threejs.

**Comment by fabienrohrer** [comment]
👍

**Comment by stefaniapedrazzi** [comment]
I'm getting this error with some of the robotbenchmark worlds, like the `square_path` and `robot_programming`. Do you have the same?

```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value).now is not a function
    at mn.getDelta (webots.min.js?R2019b:1)
    at THREE.EffectComposer.render (webots.min.js?R2019b:1)
    at e.value (webots.min.js?R2019b:1)
    at e.onTextureLoad (webots.min.js?R2019b:1)
    at e.value (webots.min.js?R2019b:1)
    at webots.min.js?R2019b:1
    at HTMLImageElement.i (webots.min.js?R2019b:1)
```

**Comment by stefaniapedrazzi** [comment]
Sorry, forget my previous comment. It is three.js version 105 that causes the issue.

**Comment by fabienrohrer** [comment]
Phew 😄

**Pull request merged**
