### PR TITLE
Removed useless alpha channels, optimized PNG file sizes

### LINKED ISSUE #330: Buggy rendering order with ElevationGrid
**Describe the Bug**
Some parts of the ElevationGrid are wrongly rendered above others.

**Steps to Reproduce**
1. Go to "tests/api/worlds/pen_elevation_grid.wbt"
2. Change the BOARD shape texture to make it more visible.

**Screenshots**

elevation_grid_bug

**System**
 - Operating System: Linux Ubuntu 18.04
 - Graphics Card: NVIDIA  GeForce GT 740/PCIe/SSE2

### PR DESCRIPTION
**Pull request by omichel**
Fixes #330.
Several PNG files were containing a useless alpha channel.

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
Note that this PNG file needs to have a alpha channel given that it is a completely transparent texture:
- `tests/api/worlds/textures/noise_mask_transparent.png`

**Comment by omichel** [comment]
> Note that this PNG file needs to have a alpha channel given that it is a completely transparent texture:
>
>-    tests/api/worlds/textures/noise_mask_transparent.png

It has, but the new version is smaller because I removed useless data from the PNG file.

**Comment by omichel** [comment]
There are many other PNG images that seem wrong to me, for example: [asphalt_roughness.png](https://github.com/omichel/webots/blob/master/projects/appearances/protos/textures/asphalt/asphalt_roughness.png) weights 3,479,027 bytes whereas it's JPEG equivalent (with 95% quality) is only 1,790,422 bytes. I believe we should be very careful when adding PNG textures and always try to add the JPEG equivalent if smaller and if no transparency is needed.

**Comment by DavidMansolino** [comment]
Yes, when switching to PBR a lot of the new textures generated were in PNG :-/

**Comment by omichel** [comment]
We should take care of them in a separate PR, as it not related to the alpha channel.

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
👍

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
👍

**Pull request merged**
