### PR TITLE
Write changelog with a single word

### PR DESCRIPTION
**Pull request by omichel**
I believe it is more standard this way.
https://cyberbotics.com/doc/reference/changelog?version=hotfix-change-log

### CODE REVIEW

**Comment by omichel** [comment]
👍

**Comment by fabienrohrer** [comment]
👀

**Comment by fabienrohrer** [comment]
Sorry, I still found some references to the old files:

```
docs/blog/Webots-2019-b-release.md:We're going to talk about some of them here, but for a comprehensive list of changes please refer to the ChangeLog, found [here](https://cyberbotics.com/doc/reference/change-log-r2019).
src/packaging/files.txt:change_logs/
src/packaging/files.txt:change_logs/*.html
src/webots/gui/WbWebotsUpdateDialog.cpp:                       "Check the change log: "
src/webots/gui/WbWebotsUpdateDialog.cpp:                       "href=\"https://cyberbotics.com/doc/reference/change-log\">https://cyberbotics.com/doc/"
src/webots/gui/WbWebotsUpdateDialog.cpp:                       "reference/change-log</a>")
src/webots/gui/WbAboutBox.cpp:  description->setText("<a style='color: #5DADE2;' href='https://cyberbotics.com/doc/reference/change-log'>Changelog</a>");
```

**Comment by omichel** [comment]
Thank you for the tests. I believe I fixed all of them (note: `files.txt` is a generated file).

👍

**Comment by omichel** [comment]
👍

**Pull request merged**
