### PR TITLE
Refactor Post-Processing for Cameras

### PR DESCRIPTION
**Pull request by tn12787**
This PR refactors camera post-processing to function in the same way as for `WbViewpoint` and `WbVirtualRealityHeadset`.

GTAO + Bloom coming in a separate PR.

The one caveat is still that we must manually apply the spherical camera merge as it is not linked to any single viewport.

### CODE REVIEW

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
👍

**Comment by fabienrohrer** [comment]
👀

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
test me

**Comment by tn12787** [comment]
👍 (unit tests have passed)

**Comment by tn12787** [comment]
Thank you for the review! Things seem to be much cleaner now.

**Pull request merged**
