### PR TITLE
Fix Floor proto

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Address #304:
- Floor PROTO instances in `humanoid_sprint.wbt` are outdated
- texture mapping in Floor PROTO is wrong and displays mirrored textured

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
test me

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
