### PR TITLE
Fix Various Crash in Python API.

### LINKED ISSUE #88: Python library crash when calling getRangeImage() too early
**Describe the Bug**

Ditto
Reported there: https://www.cyberbotics.com/forum?message=8730

**Steps to Reproduce**

1. Open 'pioneer3at.wbt' in Webots
2. Change the Sick for a Kinect
3. Attach the following new Python controller:

```python
from controller import Robot

robot = Robot()
timestep = int(robot.getBasicTimeStep())

kinectrange = robot.getRangeFinder("kinect range")
kinectrange.enable(timestep)
# robot.step(timestep)
image = kinectrange.getRangeImage()

while robot.step(timestep) != -1:
    pass
```

4. Restart the world and run the simulation
5. The controller crashes with this stack:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   _controller.so                	0x000000010befd6ed _wrap_RangeFinder_getRangeImage(_object*, _object*) + 317
1   org.python.python             	0x00007fff4cf95bf0 PyEval_EvalFrameEx + 1102
2   org.python.python             	0x00007fff4cf9b73e 0x7fff4cf16000 + 546622
3   org.python.python             	0x00007fff4cf9945a PyEval_EvalFrameEx + 15544
4   org.python.python             	0x00007fff4cf95588 PyEval_EvalCodeEx + 1540
5   org.python.python             	0x00007fff4cf94f7e PyEval_EvalCode + 32
6   org.python.python             	0x00007fff4cfb4069 0x7fff4cf16000 + 647273
7   org.python.python             	0x00007fff4cfb4110 PyRun_FileExFlags + 130
8   org.python.python             	0x00007fff4cfb3c8f PyRun_SimpleFileExFlags + 719
9   org.python.python             	0x00007fff4cfc56fc Py_Main + 3176
10  libdyld.dylib                 	0x00007fff6fd6fed9 start + 1
```

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #88 (amongst other).

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by fabienrohrer** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Pull request merged**
