### PR TITLE
Fix Connectors with SolidMergers

### PR DESCRIPTION
**Pull request by fabienrohrer**
When Connectors are used inside a SolidMerger, the connection (snapOrigin) is shifted because the rotations between the SolidMerger and the Connector are dealt in a too simplistic way.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
👍

**Pull request merged**
