### PR TITLE
Use Roughness for Infra-Red Distance Sensors.

### PR DESCRIPTION
**Pull request by DavidMansolino**
This PR improves the infrared distance sensor model by taking into account the roughness of the surface in case of PBR surface.

https://www.cyberbotics.com/doc/reference/distancesensor?version=feature-roughness-distance-sensor#infra-red-sensors

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1: 

(The `(1 - 0.5 * roughness(occlusion)` factor is empirical, I tested various coefficients in order to get realistic behavior, I have unfortunately not been able to find any publication about this).

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
test me

**Pull request merged**
