### PR TITLE
Fix Geometry Update not Awakening Solids

### LINKED ISSUE #409: ElevationGrid does not update boundingobject
**Bug description**
When an elevationGrid is defined, it works fine with respect to collision. However, when a supervisor is used to change the height parameters of the elevationGrid, the visual appearance is updated correctly, but the elevationGrid's collision no longer works properly. The elevationgrid seems still be using its old bounding object, rather than the new one which should follow the updated height values. I also noticed, that before changing height parameters with the supervisor, if you change the position of the elevationgrid and then apply the supervisor's height update, then the problem is no more present and the elevation grid's collision works as expected.

**Steps to reproduce**
Using a supervisor, change the height field parameters of an already defined elevationgrid and then have something collide with the elevationgrid.

**Expected behavior**
I would expect the collision of the elevationgrid to work with the new height values from the supervisor.

**System**
 - Operating System: Linux Ubuntu 18.04
 - Graphics Card:

### PR DESCRIPTION
**Pull request by DavidMansolino**
Attempt to fix #409

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Pull request merged**
