### PR TITLE
Cleanup-up anti-aliasing preferences

### LINKED ISSUE #190: Main 3D View Anti-Aliasing Preference Should be a Checkbox
**Describe the Bug**
The main 3d view anti-aliasing preference should be a checkbox since the only options are 'enabled' or 'disabled'.

**Screenshots**
capture

### PR DESCRIPTION
**Pull request by omichel**
Fixes #190.

### CODE REVIEW

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
👍

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
Thank you for the review. I already updated the telemetry script which can handle the new OpenGL options.
👍

**Pull request merged**
