### PR TITLE
Fix Tinkerbot and BB8 Location.

### LINKED ISSUE #224: Tinkerbot Project Location is Wrong
**Describe the Bug**
The tinkerbot project does not follow our hierarchy rule (projects/robots/manufacturer/robot_name/)

**Expected behavior**
It should be located in `projects/robots/kinematics/tinkerbots`.

Was this made on purpose to avoid 'kinematics' problematic name ?

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #224.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by fabienrohrer** [comment]
👀

**Comment by DavidMansolino** [comment]
Thank you for the tests

**Pull request merged**
