### PR TITLE
Fixed used of space protected WEBOTS_HOME_PATH variable

### LINKED ISSUE #105: Recompile error for python
**Describe the Bug**
I followed the steps described [here](https://cyberbotics.com/doc/guide/using-python#windows-installation). MSYS2 has all requirements. However I get the following error after issuing `make` command
```
swig -c++ -python -outdir "C:/Program\ Files/Webots/lib/python36/" -I"C:/Program\ Files/Webots/include/controller/cpp" -I"C:/Program\ Files/Webots/include/controller/c" -o controller36.cpp controller.i
controller.i:115: Error: Unable to find 'webots/Device.hpp'
controller.i:121: Error: Unable to find 'webots/Accelerometer.hpp'
controller.i:127: Error: Unable to find 'webots/Brake.hpp'
controller.i:154: Error: Unable to find 'webots/camera_recognition_object.h'
controller.i:299: Error: Unable to find 'webots/Camera.hpp'
controller.i:307: Error: Unable to find 'webots/Compass.hpp'
controller.i:313: Error: Unable to find 'webots/Connector.hpp'
controller.i:367: Error: Unable to find 'webots/ImageRef.hpp'
controller.i:368: Error: Unable to find 'webots/Display.hpp'
controller.i:374: Error: Unable to find 'webots/DistanceSensor.hpp'
controller.i:385: Error: Unable to find 'webots/Emitter.hpp'
controller.i:396: Error: Unable to find 'webots/Field.hpp'
controller.i:402: Error: Unable to find 'webots/GPS.hpp'
controller.i:408: Error: Unable to find 'webots/Gyro.hpp'
controller.i:414: Error: Unable to find 'webots/InertialUnit.hpp'
controller.i:420: Error: Unable to find 'webots/Joystick.hpp'
controller.i:426: Error: Unable to find 'webots/Keyboard.hpp'
controller.i:432: Error: Unable to find 'webots/LED.hpp'
controller.i:440: Error: Unable to find 'webots/lidar_point.h'
controller.i:497: Error: Unable to find 'webots/Lidar.hpp'
controller.i:505: Error: Unable to find 'webots/LightSensor.hpp'
controller.i:511: Error: Unable to find 'webots/utils/Motion.hpp'
controller.i:517: Error: Unable to find 'webots/Motor.hpp'
controller.i:542: Error: Unable to find 'webots/mouse_state.h'
controller.i:544: Error: Unable to find 'webots/Mouse.hpp'
controller.i:569: Error: Unable to find 'webots/Node.hpp'
controller.i:575: Error: Unable to find 'webots/Pen.hpp'
controller.i:581: Error: Unable to find 'webots/PositionSensor.hpp'
controller.i:606: Error: Unable to find 'webots/radar_target.h'
controller.i:625: Error: Unable to find 'webots/Radar.hpp'
controller.i:686: Error: Unable to find 'webots/RangeFinder.hpp'
controller.i:698: Error: Unable to find 'webots/Receiver.hpp'
controller.i:706: Error: Unable to find 'webots/Skin.hpp'
controller.i:712: Error: Unable to find 'webots/Speaker.hpp'
controller.i:718: Error: Unable to find 'webots/TouchSensor.hpp'
controller.i:1009: Error: Unable to find 'webots/Robot.hpp'
controller.i:1015: Error: Unable to find 'webots/DifferentialWheels.hpp'
controller.i:1021: Error: Unable to find 'webots/Supervisor.hpp'
make: *** [Makefile:99: controller36.cpp] Error 1
```
All help is appreciated. Also do I have to recompile to use 3.6.5 instead of 3.7 version of python?

### PR DESCRIPTION
**Pull request by omichel**
Fixes #105.

### CODE REVIEW

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
👍

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
All the Makefiles were fixed, so that when renaming "webots" to "webots 2" on Windows, everything compiles nicely, except for `projects/vehicles/controllers/ros_automobile` which we won't fix because it is not well designed (it shouldn't recompile source code already compiled elsewhere) and will be replaced by a ROS python controller soon.

👍

**Comment by DavidMansolino** [comment]
👀

**Pull request merged**
