### PR TITLE
Fix Telemetry

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix:
  - [x] Add build date/time to distinguish between release and development version.
  - [x] Handle cancel world loading.

Not sure if we want to merge this into master (to make sure we detect development cases as soon as possible) or revision.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
@omichel may I let you handle the new parameter on the server side ?

**Comment by DavidMansolino** [comment]
test me

**Comment by omichel** [comment]
This is done, the new parameters (operation=cancel and build=<unix_time_stamp>) should be taken into account in the database and displayed properly.

**Comment by DavidMansolino** [comment]
> This is done, the new parameters (operation=cancel and build=<unix_time_stamp>) should be taken into account in the database and displayed properly.

Perfect, thank you!

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
👍

**Pull request merged**
