### PR TITLE
Fix Make Profile

### PR DESCRIPTION
**Pull request by DavidMansolino**
The make profile was not working as expected:
  - It was broken from the main compilation process.
  - ODE was not 'profiled' as it was linked dynamically => ODE is now static in profile mode.

Now the output of the profiling includes WREN and ODE:
```
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
 24.89      0.59     0.59     9841     0.06     0.06  _dSolveL1T
 11.39      0.86     0.27    10163     0.03     0.03  _dSolveL1
  6.33      1.01     0.15 15416578     0.00     0.00  glm::tvec3<float, (glm::precision)0> glm::operator*<float, (glm::precision)0>(glm::tvec3<float, (glm::precision)0> const&, glm::tvec3<float, (glm::precision)0> const&)
  5.06      1.13     0.12     3105     0.04     0.15  wren::ShadowVolumeCaster::computeSilhouette(wren::LightNode*, bool)
  3.80      1.22     0.09      161     0.56     0.87  WbTriangleMesh::finalPass(WbMFVector3 const*, WbMFVector2 const*, double)
  2.32      1.28     0.06  3001714     0.00     0.00  WbTokenizer::readWord()
....
```

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
I am getting this error on Windows:
```
# * wren *
#
# copying wren.a
#
# * webots (core) *
#
make[1]: *** No rule to make target '../wren/libwren.a', needed by '../../msys64/mingw64/bin/webots.exe'.  Stop.
make: *** [Makefile:106: webots_target] Error 2
```

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
test me

**Comment by omichel** [comment]
I just fixed another link problem on Windows. Now everything seems to work fine.
However, I believe we should also test this PR on macOS before merging it.

**Comment by omichel** [comment]
Oops, sorry, but there are still problems on Windows, I cannot compile the physics plugins in profile mode, errors about ode are reported:
```
D:/msys64/home/Olivier/webots/msys64/mingw64/bin/ode.dll(ode.o):ode.cpp:(.text+0x13b5): undefined reference to `operator delete[](void*)'
[...]
```

**Comment by DavidMansolino** [comment]
Thank you for the test and fix, I checked physic plugin recompilation and run on Linux and it is working fine, I will investigate what is not working on Windows.

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
👍

**Comment by fabienrohrer** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by omichel** [comment]
:eyes:

**Comment by fabienrohrer** [comment]
I just checked on macOS: I had to remove the `-pg` option when linking (reference https://stackoverflow.com/questions/52519907/dyld-section-not-supported-after-mojave-upgrade) . It's working now.

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
Thank you both for the test.

**Pull request merged**
