### PR TITLE
Merge revision into develop

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
No conflicts

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
The merge is blocked by the appveyor check probably because I didn't create a branch for the merge.
```continuous-integration/appveyor/branch Expected — Waiting for status to be reported```

I will close this and create a branch for the merge.

**Comment by DavidMansolino** [comment]
I will start manually the test :wink:

**Comment by DavidMansolino** [comment]
The problem is indeed linked to the fact that there is no branch and the `revision` and `develop` branches are ignored:
https://github.com/omichel/webots/blob/revision/.appveyor.yml#L5

**Comment by stefaniapedrazzi** [comment]
Thank you

**Pull request merged**
