### PR TITLE
Update icon and doc images

### PR DESCRIPTION
**Pull request by DavidMansolino**
Regenerate Doc Images + Icons for R2019b #236

https://www.cyberbotics.com/doc/guide/objects?version=update-icon-and-images

### CODE REVIEW

**Comment by DavidMansolino** [comment]
**before**:

**after**


**before**

**after**

**Comment by DavidMansolino** [comment]
I have improved the script, now 100% of the images are generated by the script without any manual edition. I checked all of them in the doc and couldn't see any issue with the cropping or background removal.

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
👀

**Pull request merged**
