### PR TITLE
Fix Windows Dependencies Makefile

### PR DESCRIPTION
**Pull request by DavidMansolino**
The windows dependencies makefile is currently broken:
  - not all the `unzip` command contains the `-o` argument which requires user interaction during the compilation process.
  - some of the dependencies are extracted at each compilation.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
This was broken in #683

**Comment by DavidMansolino** [comment]
:+1:

**Comment by omichel** [comment]
Thank you for fixing it!

**Comment by DavidMansolino** [comment]
You're welcome.

**Pull request merged**
