### PR TITLE
ABB  IRB 4600/40 arm

### PR DESCRIPTION
**Pull request by fabienrohrer**
- [x] PROTO
    - [x] Icon
- [x] worlds + controller
    - [x] IK demo
- [x] Documentation: Preview: https://cyberbotics.com/doc/guide/irb4600-40?version=feature-abb-arm
    - [x] Robot component
- [x] Log

---

Misc small modifications, not directly related:

- [x] Improve factory.wbt (texture mapping, simplify floats. )
- [x] Fix and extend `web component studio` to support robot children.
- [x] Move lady_bug.png in the common textures :-)

### CODE REVIEW

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
Notes about this PR:

- I created only one example to demonstrate inverse kinematics, as simple as possible to show IK in action.
- Replacing the IPR factory by ABB arms would be welcome but it would be also good to already review this step which is already a good/releasable milestone.
- I choose to set the default color of the arm to an "ABB orange" because the white was difficult to understand in icons/images/components.
- I also postpone the movie creation to another PR.

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
That looks very nice! However, it seems the limits of the C motor are wrong as the arm collisions with itself in a way that could be avoided by setting limits differently.

**Comment by fabienrohrer** [comment]
Good remark. I found this in the specifications, I will check this more seriously.

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
The bounds were correct but the motors a, b, c axes were inverted (it was working at some point, I probably messed something).
It is now compliant with the specifications:

specs1
specs2

I fixed the alignment of the hand too.

**Comment by fabienrohrer** [comment]
test me

**Comment by fabienrohrer** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by omichel** [comment]
Thank you for the fixes. The last axis is still rotating weirdly, better than before, but still not well centered. It looks not very precise. Such arms should have a very good precision.

**Comment by fabienrohrer** [comment]
This is right. I have to redo this mesh.

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
👍

**Comment by fabienrohrer** [comment]
Yes, I will do a movie soon: I have funny things under the hood :-D :

spirograph 1
spirograph 2
spirograph 3

**Pull request merged**
