### PR TITLE
Fix Matlab Controller on Windows

### LINKED ISSUE #63: Matlab Controllers Broken
**Describe the Bug**
Matlab controllers are broken (this might be recent as it was working ~1month ago).

**Steps to Reproduce**
1. Open the matlab sample and run it.

**Screenshots**
```
MATLAB crash file:C:\Users\David\AppData\Local\Temp\matlab_crash_dump.8892-1:


--------------------------------------------------------------------------------
             Assertion detected at mer. déc. 12 04:09:53 2018 +0100
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown hardware 
  Graphics card 1          : NVIDIA ( 0x10de ) NVIDIA GeForce GTX 970 Version 25.21.14.1694 (2018-11-12)
  Java Crash Report        : C:\Users\David\AppData\Local\Temp\hs_error_pid8892.log
  Java Version             : Java 1.8.0_144-b01 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 1376434
  MATLAB Root              : C:\Program Files\MATLAB\R2018a
  MATLAB Version           : 9.4.0.813654 (R2018a)
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 10 Famille
  Process ID               : 8892
  Processor ID             : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Session Key              : 6e2697c1-508e-4e34-8cbd-6994f1ad538c
  Window System            : Version 10.0 (Build 17134)

Fault Count: 1


Assertion in void __cdecl `anonymous-namespace'::mwJavaAbort(void) at b:\matlab\src\jmi\jmi\javainit.cpp line 1461

Register State (captured):
  RAX = 00000000fea22ef8  RBX = 0000000000000000
  RCX = 00000000043ebed0  RDX = 0000000000000000
  RSP = 00000000043ebe50  RBP = 0000000021218858
  RSI = 00000000fea22ef8  RDI = 00000000fea22ef8
 
   R8 = 00008d9ae3973cff   R9 = 00007ffd17950000
  R10 = 00000000fe95a298  R11 = 00000000fea12eec
  R12 = 00000000043ec510  R13 = 00000000fea12e28
  R14 = 00000000fea22e78  R15 = 0000000021218858
 
  RIP = 00000000fe81c44a  EFL = 00000206
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (captured):
[  0] 0x00000000fe816063                              bin\win64\libmwfl.dll+00155747
[  1] 0x00000000fe814658                              bin\win64\libmwfl.dll+00149080
[  2] 0x00000000fe817f68                              bin\win64\libmwfl.dll+00163688
[  3] 0x00000000fe81780e                              bin\win64\libmwfl.dll+00161806
[  4] 0x00000000fe81bdc8                              bin\win64\libmwfl.dll+00179656
[  5] 0x00000000211abcec                                  bin\win64\jmi.dll+00703724
[  6] 0x0000000059b36d1d C:\Program Files\MATLAB\R2018a\sys\java\jre\win64\jre\bin\server\jvm.dll+02714909
[  7] 0x0000000059b1ef3b C:\Program Files\MATLAB\R2018a\sys\java\jre\win64\jre\bin\server\jvm.dll+02617147
[  8] 0x0000000059b37a46 C:\Program Files\MATLAB\R2018a\sys\java\jre\win64\jre\bin\server\jvm.dll+02718278
[  9] 0x0000000059b3c33c C:\Program Files\MATLAB\R2018a\sys\java\jre\win64\jre\bin\server\jvm.dll+02736956
[ 10] 0x0000000059bd2938 C:\Program Files\MATLAB\R2018a\sys\java\jre\win64\jre\bin\server\jvm.dll+03352888
[ 11] 0x00007ffd1ed4ed3d                      C:\WINDOWS\SYSTEM32\ntdll.dll+00650557
[ 12] 0x00007ffd1ecb6c86                      C:\WINDOWS\SYSTEM32\ntdll.dll+00027782
[ 13] 0x00007ffd1ed4dc6e                      C:\WINDOWS\SYSTEM32\ntdll.dll+00646254
[ 14] 0x000000018005e8fe C:\Program Files\Webots\msys64\usr\bin\msys-2.0.dll+00125182
[ 15] 0x000000018005fea8 C:\Program Files\Webots\msys64\usr\bin\msys-2.0.dll+00130728
[ 16] 0x00007ffd1ed156b8                      C:\WINDOWS\SYSTEM32\ntdll.dll+00415416
[ 17] 0x00007ffd1ecb722c                      C:\WINDOWS\SYSTEM32\ntdll.dll+00029228
[ 18] 0x00007ffd1ed4dc6e                      C:\WINDOWS\SYSTEM32\ntdll.dll+00646254
[ 19] 0x000000008044344c                                   <unknown-module>+00000000
```

**System**
 - Operating System: Windows 10
 - Matlab Version: R2018a

### PR DESCRIPTION
**Pull request by DavidMansolino**
Fix #63.

### CODE REVIEW

**Comment by DavidMansolino** [comment]
test me

**Comment by DavidMansolino** [comment]
👍

**Comment by omichel** [comment]
:eyes:

**Comment by DavidMansolino** [comment]
:+1:

**Pull request merged**
