### PR TITLE
Fix simulation_server.py for Python3

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Fix issues running `simulation_server.py` with python3 reported in https://github.com/omichel/webots/issues/363.

I will also add instructions for python 3 in the dependencies page that currently only refer to python 2.7:
https://github.com/omichel/webots/wiki/Linux-Optional-Dependencies#webots-web-service
```
sudo pip3 install --upgrade pip
sudo pip3 install websocket-client tornado nvidia-ml-py3 psutil requests
```

### CODE REVIEW

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by stefaniapedrazzi** [comment]
:-1:

**Comment by stefaniapedrazzi** [comment]
:+1:

**Comment by DavidMansolino** [comment]
This should probably target the `revision` branch.

**Comment by stefaniapedrazzi** [comment]
:+1:

**Pull request merged**
